config/routes.rb
Rails.application.routes.draw do
  root :to => "search#index", via: [:get, :post]

  match 'search(/:action)', :controller => 'search', via: [:get, :post, :patch]
  match 'search/index', :controller => 'search', as: :search, via: [:get, :post]

end

app/models/period.rb
class Period < ActiveRecord::Base

  belongs_to :state
end

app/models/state.rb
class State < ActiveRecord::Base

  ACRONYM = [
    "Acre",
    "Alagoas",
    "Amapa",
    "Amazonas",
    "Bahia",
    "Ceara",
    "Distrito Federal",
    "Espirito Santo",
    "Goias",
    "Maranhao",
    "Mato Grosso",
    "Mato Grosso do Sul",
    "Minas Gerais",
    "Para",
    "Paraiba",
    "Parana",
    "Pernambuco",
    "Piaui",
    "Rio Grande do Norte",
    "Rio Grande do Sul",
    "Rio de Janeiro",
    "Rondonia",
    "Roraima",
    "Santa Catarina",
    "Sao Paulo",
    "Sergipe",
    "Tocantins"
  ]

  has_many :periods, dependent: :destroy

  def <=> (other)
    self.name <=> other.name
  end

  def number year
    Period.find_by(state_id: self.id, year: year).number
  end

  def chart_formated
    hash_chart = {}

    self.periods.each do |period|
      hash_chart[period.year.to_s] = period.number
    end

    hash_chart
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @state = State.find_by_name(params[:name])
    @selected = @state ? @state.name : ""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Datamine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/index.html.erb
<h3> Selecione um Estado: </h3>

<%= form_for :state, url: search_path do |f| %>
  <%= select_tag :name, options_for_select(State::ACRONYM, selected: @selected) %>
  <%= f.submit "Search" %>
<% end %>

<% if @state %>
  <h1> <%= "Taxa de incidência da dengue: #{@state.name}" %> </h1>
  <%= column_chart(@state.chart_formated) %>
<% end %>